(ql:quickload :cl-ppcre)

;;(directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/Spatial/*.h")

;; FIXME 2025-09-14 11:46:09 over-matching; something to do with escaping?
;; (let* ((re (ppcre:create-scanner "^(SP[A-Z][a-z]\\S*|void) SP[A-Z][a-z]\\S*\\(.*\\)"
;;                                  :single-line-mode t
;;                                  :multi-line-mode t)))

;;   (ppcre:all-matches-as-strings
;;    re
;;    (uiop:read-file-string #P"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/Spatial/SPAffineTransform3D.h")))

(defun parse-params (paramstr)
  (loop for param in (ppcre:split ",\\s*" paramstr)
        collect (ppcre:split"\\s+" param)))

(defun parse-fn (fnstr)
  (ppcre:register-groups-bind (ret-type fn-name params)
      ("(SP[A-Z][a-z]\\S*|void) (SP[A-Z][a-z]\\S*)\\((.*)\\)" fnstr)
    (list ret-type fn-name (parse-params params))))

(defun parse-file (fname)
  (with-open-file (stream fname :direction :input)
    (loop for line = (read-line stream nil :eof)
          until (eq line :eof)
          collect (parse-fn line))))

(defun wrap-params (paramlist)
  (let* ((o (make-string-output-stream)))
    (destructuring-bind (ty param) (car paramlist)
      (format o "~a ~a" ty param))
    (loop for (ty param) in (cdr paramlist)
          do (format o ", ~a ~a" ty param))
    (get-output-stream-string o)))

(defun pointer-passthrough (param)
  (ppcre:register-groups-bind
      (nil name nil)
      ("(\\*)?([^\\[\\]]*)(\\[\\])?" param)
    name))

(defun wrap-args (paramlist)
  (let* ((o (make-string-output-stream)))
    (destructuring-bind (ty param) (car paramlist)
      (format o "~a" (pointer-passthrough param)))
    (loop for (ty param) in (cdr paramlist)
          do (format o ", ~a" (pointer-passthrough param)))
    (get-output-stream-string o)))

;; TODO 2025-09-14 22:24:08 also write out lisp defuns incl type simplification (see spatial.lisp)

(defun wrap-fns (fns to-stream)
  (format to-stream "// Autogenerated, do not edit.~%#include <Spatial/Spatial.h>~%")
  (loop for (ret-type fn-name params) in fns
        do (format to-stream "~a wrap~a(~a) {~a~a(~a);}~%"
                   ret-type
                   fn-name
                   (wrap-params params)
                   (if (string= ret-type "void") "" "return ")
                   fn-name
                   (wrap-args params))))

;; FIXME 2025-09-14 14:44:14 what's going on with trailing garbage:
;; );}
;; is(rotation, axis);}
;; 3DSetAxis(rotation, axis);}

(with-open-file (o "wrap_spatial.m" :direction :output :if-exists :overwrite)
  (wrap-fns (parse-file "spatial_fns.txt") o))
